-- MySQL Script generated by MySQL Workbench
-- Sat Jan 28 21:14:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8 ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Users` (
  `ID_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Customers` (
  `nick_name` VARCHAR(45) NOT NULL,
  `Users_ID_user` INT NOT NULL,
  UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC) VISIBLE,
  PRIMARY KEY (`Users_ID_user`),
  CONSTRAINT `fk_Customers_Users1`
    FOREIGN KEY (`Users_ID_user`)
    REFERENCES `restaurant`.`Users` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Additions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Additions` (
  `ID_addition` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`ID_addition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Menu` (
  `ID_food` INT NOT NULL AUTO_INCREMENT,
  `name_food` VARCHAR(45) NOT NULL,
  `kcal` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_food`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Orders` (
  `ID_order` INT NOT NULL AUTO_INCREMENT,
  `date_of_order` DATE NOT NULL,
  `order_status` VARCHAR(25) NOT NULL,
  `Customers_Users_ID_user` INT NOT NULL,
  `Additions_ID_addition` INT NULL,
  `Menu_ID_food` INT NULL,
  PRIMARY KEY (`ID_order`, `Customers_Users_ID_user`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_Users_ID_user` ASC) VISIBLE,
  INDEX `fk_Orders_Additions1_idx` (`Additions_ID_addition` ASC) VISIBLE,
  INDEX `fk_Orders_Menu1_idx` (`Menu_ID_food` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_Users_ID_user`)
    REFERENCES `restaurant`.`Customers` (`Users_ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Additions1`
    FOREIGN KEY (`Additions_ID_addition`)
    REFERENCES `restaurant`.`Additions` (`ID_addition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Menu1`
    FOREIGN KEY (`Menu_ID_food`)
    REFERENCES `restaurant`.`Menu` (`ID_food`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Employees` (
  `role` VARCHAR(45) NOT NULL,
  `nick_name` VARCHAR(45) NOT NULL,
  `Users_ID_user` INT NOT NULL,
  PRIMARY KEY (`Users_ID_user`),
  UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Users1`
    FOREIGN KEY (`Users_ID_user`)
    REFERENCES `restaurant`.`Users` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Delivery` (
  `ID_dilivery` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(6) NOT NULL,
  `invoice` VARCHAR(45) NULL,
  `Orders_ID_order` INT NOT NULL,
  `Orders_Customers_Users_ID_user` INT NOT NULL,
  PRIMARY KEY (`ID_dilivery`),
  INDEX `fk_Delivery_Orders1_idx` (`Orders_ID_order` ASC, `Orders_Customers_Users_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Orders1`
    FOREIGN KEY (`Orders_ID_order` , `Orders_Customers_Users_ID_user`)
    REFERENCES `restaurant`.`Orders` (`ID_order` , `Customers_Users_ID_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Address` (
  `ID_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `room_number` VARCHAR(5) NOT NULL,
  `postal_index` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Adress_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Adress_customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Address_ID_adress` INT NOT NULL,
  `Customers_Users_ID_user` INT NOT NULL,
  PRIMARY KEY (`id`, `Address_ID_adress`, `Customers_Users_ID_user`),
  INDEX `fk_Adress_customer_Customers1_idx` (`Customers_Users_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_Adress_customer_Address1`
    FOREIGN KEY (`Address_ID_adress`)
    REFERENCES `restaurant`.`Address` (`ID_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adress_customer_Customers1`
    FOREIGN KEY (`Customers_Users_ID_user`)
    REFERENCES `restaurant`.`Customers` (`Users_ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(250) NOT NULL,
  `Menu_ID_food` INT NOT NULL,
  `Customers_Users_ID_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_Comments_Menu1_idx` (`Menu_ID_food` ASC) VISIBLE,
  INDEX `fk_Comments_Customers1_idx` (`Customers_Users_ID_user` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Menu1`
    FOREIGN KEY (`Menu_ID_food`)
    REFERENCES `restaurant`.`Menu` (`ID_food`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Customers1`
    FOREIGN KEY (`Customers_Users_ID_user`)
    REFERENCES `restaurant`.`Customers` (`Users_ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurant`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `Employees_Users_ID_user` INT NOT NULL,
  `Delivery_ID_dilivery` INT NOT NULL,
  PRIMARY KEY (`idSupplier`, `Employees_Users_ID_user`, `Delivery_ID_dilivery`),
  INDEX `fk_Supplier_Employees1_idx` (`Employees_Users_ID_user` ASC) VISIBLE,
  INDEX `fk_Supplier_Delivery1_idx` (`Delivery_ID_dilivery` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Employees1`
    FOREIGN KEY (`Employees_Users_ID_user`)
    REFERENCES `restaurant`.`Employees` (`Users_ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_Delivery1`
    FOREIGN KEY (`Delivery_ID_dilivery`)
    REFERENCES `restaurant`.`Delivery` (`ID_dilivery`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
